# All Steps are included in this file

BASE:=base
BASE_FILES_ADDR:=devices\base

SYSTEM_PROP:=$(DEVICE)\prop\system.prop

BOOT_IMAGE:=$(DEVICE)\boot\boot.img

UPDATE_SCRIPT_ADDR:=$(DEVICE)\

# You should unzip ota rom to ota\
OTA_ROM_ADDR:=$(DEVICE)\ota\

TARGET_ANDROID_VERSION:=5.1
OUT_FILES_ADDR:=$(DEVICE)\out\
